### ISSUE TITLE
Google Play Music Desktop Player does not find DBus module (T6788)

### ISSUE THREAD

**Issue by celticmagic** [getsolus/packages#38]
<div dir="rtl"><b>Jon</b>&nbsp;(<em>&#35;jngbsn</em>),&nbsp;2018-08-15&nbsp;07:17:26&nbsp;UTC</div><br/>

Relatively fresh install, when launching GPMDP in the console it gives this output:

```
error: Uncaught Exception. message=Cannot find module 'dbus', stack=Error: Cannot find module 'dbus'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/usr/share/gpmdp/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/linux/mediaKeysDBus.js:11:13)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/linux/mediaKeysDBus.js:48:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/linux/index.js:11:1)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/linux/index.js:14:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/index.js:13:1)
    at Object.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/main/features/index.js:14:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at App.<anonymous> (/usr/share/gpmdp/resources/app.asar/build/index.js:183:5)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7), code=MODULE_NOT_FOUND

```

dbus and dbus-devel are both installed. Nodejs dependency is missing in build maybe?

**Comment by davidjharder** [comment]
Ancient. Closing
