### ISSUE TITLE
Vorta does not start

### ISSUE THREAD

**Issue by endumiuz** [getsolus/packages#4542]
### Please confirm there isn't an open report for this issue

- [X] I have searched through bug reports

### Summary

Vorta doesn't start since the last update

### Steps to reproduce

Try to start Vorta

### Expected result

It should start

### Actual result

```
kim@kim-solus ~> vorta
2024-12-08 16:07:06,153 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.9.1', 'gui_scripts', 'vorta')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vorta/__main__.py", line 84, in main
    from vorta.application import VortaApp
  File "/usr/lib/python3.11/site-packages/vorta/application.py", line 24, in <module>
    from vorta.views.main_window import MainWindow
  File "/usr/lib/python3.11/site-packages/vorta/views/main_window.py", line 4, in <module>
    from PyQt6 import QtCore, uic
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/PyQt6/uic/__init__.py'
```

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

GNOME

### System details

```
System:
  Host: kim-solus Kernel: 6.11.10-310.current arch: x86_64 bits: 64
  Desktop: GNOME v: 47.2 Distro: Solus 4.6 convergence
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: ROG STRIX B550-F GAMING v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 3405
    date: 12/13/2023
CPU:
  Info: 8-core AMD Ryzen 7 5800X [MT MCP] speed (MHz): avg: 1752
    min/max: 550/4851
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Navi 32 [Radeon RX 7700 XT /
    7800 XT] driver: amdgpu v: kernel
  Display: wayland server: X.Org v: 24.1.4 with: Xwayland v: 24.1.4
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 5120x1440~240Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.8 renderer: AMD
    Radeon RX 7800 XT (radeonsi navi32 LLVM 18.1.8 DRM 3.59
    6.11.10-310.current)
Network:
  Device-1: Intel Ethernet I225-V driver: igc
Drives:
  Local Storage: total: 17.28 TiB used: 12.1 TiB (70.0%)
Info:
  Memory: total: 64 GiB note: est. available: 62.71 GiB used: 6.17 GiB (9.8%)
  Processes: 406 Uptime: 37m Shell: fish inxi: 3.3.36

```

### Other comments

There is also a newer version available, so maybe it just needs to be updated: https://github.com/borgbase/vorta/releases

**Comment by davidjharder** [comment]
Confirmed
