### ISSUE TITLE
Etcher stopped running after the update

### ISSUE THREAD

**Issue by AlexanderZhirov** [getsolus/packages#778]
### Summary

After the update, Etcher stopped running. Through the terminal writes these errors:

```
[Axios v1.7.9+5945ab1f] Transitional option 'clarifyTimeoutError' has been deprecated since v1.0.0 and will be removed in the near future
[Axios v1.7.9+5945ab1f] Transitional option 'forcedJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
[Axios v1.7.9+5945ab1f] Transitional option 'silentJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
libva error: vaGetDriverNames() failed with unknown libva error
libva error: vaGetDriverNames() failed with unknown libva error
libva error: vaGetDriverNames() failed with unknown libva error
{"message":"Request failed with status code 404","stack":"Error: Request failed with status code 404\n    at createError (/usr/share/etcher/resources/app/generated/etcher.js:1:538018)\n    at settle (/usr/share/etcher/resources/app/generated/etcher.js:1:537708)\n    at IncomingMessage.handleStreamEnd (/usr/share/etcher/resources/app/generated/etcher.js:1:536494)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"https://balena.io/etcher/static/config.json","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.7.9+5945ab1f"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}}}
[3514:1107/010034.138026:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
/usr/bin/etcher: line 10:  3514 Trace/breakpoint trap   (core dumped) "${script_dir}"/balena-etcher-electron.bin "$@"
```

But it starts via `sudo`.

### Steps to reproduce

Launching the program

### Expected result

Running the program on behalf of the user

### Actual result

The program is launched only via the terminal from `root`

### Environment

- [ ] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

MATE

### System details

OS: Solus x86_64 
Kernel: 6.5.9-262.current 
DE: MATE 1.27.0 
CPU: Intel i7-3770 (8) @ 3.900GHz 
GPU: NVIDIA GeForce GTX 1050 Ti

**Comment by joebonrichie** [comment]
Run with `--disable-gpu` or `--no-sandbox` as a workaround for now. Will try to get it fixed for next sync.

**Comment by AlexanderZhirov** [comment]
@joebonrichie With `--no-sandbox` worked
