### ISSUE TITLE
pre-commit-hooks: package_checks.py fails for nested rundeps

### ISSUE THREAD

**Issue by Staudey** [getsolus/packages#860]
### Summary

@malfisya discovered that the pre-commit checks don't work for packages with nested rundeps. For example `kdevelop`, which has the following `rundeps` section:

```
rundeps    :
    - cppcheck
    - devel :
        - threadweaver-devel
```

Trying to commit  a change for this package leads to the following error:

```
Package checks failed: /home/alfisya/Documents/Solus-Dev/solus-packages/common/CI/package_checks.py packages/k/kdevelop/package.yml packages/k/kdevelop/pspec_x86_64.xml
Output:
  Checking files: packages/k/kdevelop/package.yml, packages/k/kdevelop/pspec_x86_64.xml
  Traceback (most recent call last):
    File "/home/alfisya/Documents/Solus-Dev/solus-packages/common/CI/package_checks.py", line 423, in <module>
      exit(checker.run())
    File "/home/alfisya/Documents/Solus-Dev/solus-packages/common/CI/package_checks.py", line 377, in run
      results = [result for check in self.checks
    File "/home/alfisya/Documents/Solus-Dev/solus-packages/common/CI/package_checks.py", line 378, in <listcomp>
      for result in check(self.git, self.files, self.commits, self.base).run()]
    File "/home/alfisya/Documents/Solus-Dev/solus-packages/common/CI/package_checks.py", line 198, in run
      results = [self._check_deps(deps, file)
    File "/home/alfisya/Documents/Solus-Dev/solus-packages/common/CI/package_checks.py", line 198, in <listcomp>
      results = [self._check_deps(deps, file)
    File "/home/alfisya/Documents/Solus-Dev/solus-packages/common/CI/package_checks.py", line 206, in _check_deps
      exp = sorted(cur, key=self._sort)
    File "/home/alfisya/Documents/Solus-Dev/solus-packages/common/CI/package_checks.py", line 216, in _sort
      if pkg.startswith('pkgconfig('):
  AttributeError: 'dict' object has no attribute 'startswith'
```

### Steps to reproduce

1. Make a change to a package with nested `rundeps` section like `kdevelop`
2. Try to `git commit`

### Expected result

You can commit the changes

### Actual result

Above error message appears

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Other

### System details

N/A

**Comment by ReillyBrogan** [comment]
Oh I hit this in my quazip PR too

**Comment by davidjharder** [comment]
This is fixed now
